/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JsonViewerRouteImport } from './routes/json-viewer'
import { Route as JsonToTableRouteImport } from './routes/json-to-table'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as JsonDiffRouteImport } from './routes/json-diff'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceLinkIdRouteImport } from './routes/workspace.link.$id'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonViewerRoute = JsonViewerRouteImport.update({
  id: '/json-viewer',
  path: '/json-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToTableRoute = JsonToTableRouteImport.update({
  id: '/json-to-table',
  path: '/json-to-table',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonDiffRoute = JsonDiffRouteImport.update({
  id: '/json-diff',
  path: '/json-diff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceLinkIdRoute = WorkspaceLinkIdRouteImport.update({
  id: '/link/$id',
  path: '/link/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-to-table': typeof JsonToTableRoute
  '/json-viewer': typeof JsonViewerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/link/$id': typeof WorkspaceLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-to-table': typeof JsonToTableRoute
  '/json-viewer': typeof JsonViewerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/link/$id': typeof WorkspaceLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-to-table': typeof JsonToTableRoute
  '/json-viewer': typeof JsonViewerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/link/$id': typeof WorkspaceLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/json-diff'
    | '/json-formatter'
    | '/json-to-table'
    | '/json-viewer'
    | '/sitemap.xml'
    | '/workspace'
    | '/workspace/link/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/json-diff'
    | '/json-formatter'
    | '/json-to-table'
    | '/json-viewer'
    | '/sitemap.xml'
    | '/workspace'
    | '/workspace/link/$id'
  id:
    | '__root__'
    | '/'
    | '/json-diff'
    | '/json-formatter'
    | '/json-to-table'
    | '/json-viewer'
    | '/sitemap.xml'
    | '/workspace'
    | '/workspace/link/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JsonDiffRoute: typeof JsonDiffRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  JsonToTableRoute: typeof JsonToTableRoute
  JsonViewerRoute: typeof JsonViewerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-viewer': {
      id: '/json-viewer'
      path: '/json-viewer'
      fullPath: '/json-viewer'
      preLoaderRoute: typeof JsonViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-table': {
      id: '/json-to-table'
      path: '/json-to-table'
      fullPath: '/json-to-table'
      preLoaderRoute: typeof JsonToTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-diff': {
      id: '/json-diff'
      path: '/json-diff'
      fullPath: '/json-diff'
      preLoaderRoute: typeof JsonDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/link/$id': {
      id: '/workspace/link/$id'
      path: '/link/$id'
      fullPath: '/workspace/link/$id'
      preLoaderRoute: typeof WorkspaceLinkIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceLinkIdRoute: typeof WorkspaceLinkIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceLinkIdRoute: WorkspaceLinkIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JsonDiffRoute: JsonDiffRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  JsonToTableRoute: JsonToTableRoute,
  JsonViewerRoute: JsonViewerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
