/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JsonViewerRouteImport } from './routes/json-viewer'
import { Route as JsonToTableRouteImport } from './routes/json-to-table'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as JsonDiffRouteImport } from './routes/json-diff'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesViewJsonAsTableRouteImport } from './routes/guides.view-json-as-table'
import { Route as GuidesReadLargeJsonFilesRouteImport } from './routes/guides.read-large-json-files'
import { Route as GuidesJsonVsCsvRouteImport } from './routes/guides.json-vs-csv'
import { Route as GuidesJsonSyntaxExplainedRouteImport } from './routes/guides.json-syntax-explained'
import { Route as GuidesHowToValidateJsonRouteImport } from './routes/guides.how-to-validate-json'
import { Route as GuidesHowToFormatJsonRouteImport } from './routes/guides.how-to-format-json'
import { Route as GuidesHowToCompareJsonFilesRouteImport } from './routes/guides.how-to-compare-json-files'
import { Route as WorkspaceLinkIdRouteImport } from './routes/workspace.link.$id'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonViewerRoute = JsonViewerRouteImport.update({
  id: '/json-viewer',
  path: '/json-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToTableRoute = JsonToTableRouteImport.update({
  id: '/json-to-table',
  path: '/json-to-table',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonDiffRoute = JsonDiffRouteImport.update({
  id: '/json-diff',
  path: '/json-diff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesViewJsonAsTableRoute = GuidesViewJsonAsTableRouteImport.update({
  id: '/guides/view-json-as-table',
  path: '/guides/view-json-as-table',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesReadLargeJsonFilesRoute =
  GuidesReadLargeJsonFilesRouteImport.update({
    id: '/guides/read-large-json-files',
    path: '/guides/read-large-json-files',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesJsonVsCsvRoute = GuidesJsonVsCsvRouteImport.update({
  id: '/guides/json-vs-csv',
  path: '/guides/json-vs-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesJsonSyntaxExplainedRoute =
  GuidesJsonSyntaxExplainedRouteImport.update({
    id: '/guides/json-syntax-explained',
    path: '/guides/json-syntax-explained',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowToValidateJsonRoute = GuidesHowToValidateJsonRouteImport.update({
  id: '/guides/how-to-validate-json',
  path: '/guides/how-to-validate-json',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHowToFormatJsonRoute = GuidesHowToFormatJsonRouteImport.update({
  id: '/guides/how-to-format-json',
  path: '/guides/how-to-format-json',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHowToCompareJsonFilesRoute =
  GuidesHowToCompareJsonFilesRouteImport.update({
    id: '/guides/how-to-compare-json-files',
    path: '/guides/how-to-compare-json-files',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceLinkIdRoute = WorkspaceLinkIdRouteImport.update({
  id: '/link/$id',
  path: '/link/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-to-table': typeof JsonToTableRoute
  '/json-viewer': typeof JsonViewerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/guides/how-to-compare-json-files': typeof GuidesHowToCompareJsonFilesRoute
  '/guides/how-to-format-json': typeof GuidesHowToFormatJsonRoute
  '/guides/how-to-validate-json': typeof GuidesHowToValidateJsonRoute
  '/guides/json-syntax-explained': typeof GuidesJsonSyntaxExplainedRoute
  '/guides/json-vs-csv': typeof GuidesJsonVsCsvRoute
  '/guides/read-large-json-files': typeof GuidesReadLargeJsonFilesRoute
  '/guides/view-json-as-table': typeof GuidesViewJsonAsTableRoute
  '/guides/': typeof GuidesIndexRoute
  '/workspace/link/$id': typeof WorkspaceLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-to-table': typeof JsonToTableRoute
  '/json-viewer': typeof JsonViewerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/guides/how-to-compare-json-files': typeof GuidesHowToCompareJsonFilesRoute
  '/guides/how-to-format-json': typeof GuidesHowToFormatJsonRoute
  '/guides/how-to-validate-json': typeof GuidesHowToValidateJsonRoute
  '/guides/json-syntax-explained': typeof GuidesJsonSyntaxExplainedRoute
  '/guides/json-vs-csv': typeof GuidesJsonVsCsvRoute
  '/guides/read-large-json-files': typeof GuidesReadLargeJsonFilesRoute
  '/guides/view-json-as-table': typeof GuidesViewJsonAsTableRoute
  '/guides': typeof GuidesIndexRoute
  '/workspace/link/$id': typeof WorkspaceLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/json-diff': typeof JsonDiffRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-to-table': typeof JsonToTableRoute
  '/json-viewer': typeof JsonViewerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/guides/how-to-compare-json-files': typeof GuidesHowToCompareJsonFilesRoute
  '/guides/how-to-format-json': typeof GuidesHowToFormatJsonRoute
  '/guides/how-to-validate-json': typeof GuidesHowToValidateJsonRoute
  '/guides/json-syntax-explained': typeof GuidesJsonSyntaxExplainedRoute
  '/guides/json-vs-csv': typeof GuidesJsonVsCsvRoute
  '/guides/read-large-json-files': typeof GuidesReadLargeJsonFilesRoute
  '/guides/view-json-as-table': typeof GuidesViewJsonAsTableRoute
  '/guides/': typeof GuidesIndexRoute
  '/workspace/link/$id': typeof WorkspaceLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/json-diff'
    | '/json-formatter'
    | '/json-to-table'
    | '/json-viewer'
    | '/sitemap.xml'
    | '/workspace'
    | '/guides/how-to-compare-json-files'
    | '/guides/how-to-format-json'
    | '/guides/how-to-validate-json'
    | '/guides/json-syntax-explained'
    | '/guides/json-vs-csv'
    | '/guides/read-large-json-files'
    | '/guides/view-json-as-table'
    | '/guides/'
    | '/workspace/link/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/json-diff'
    | '/json-formatter'
    | '/json-to-table'
    | '/json-viewer'
    | '/sitemap.xml'
    | '/workspace'
    | '/guides/how-to-compare-json-files'
    | '/guides/how-to-format-json'
    | '/guides/how-to-validate-json'
    | '/guides/json-syntax-explained'
    | '/guides/json-vs-csv'
    | '/guides/read-large-json-files'
    | '/guides/view-json-as-table'
    | '/guides'
    | '/workspace/link/$id'
  id:
    | '__root__'
    | '/'
    | '/json-diff'
    | '/json-formatter'
    | '/json-to-table'
    | '/json-viewer'
    | '/sitemap.xml'
    | '/workspace'
    | '/guides/how-to-compare-json-files'
    | '/guides/how-to-format-json'
    | '/guides/how-to-validate-json'
    | '/guides/json-syntax-explained'
    | '/guides/json-vs-csv'
    | '/guides/read-large-json-files'
    | '/guides/view-json-as-table'
    | '/guides/'
    | '/workspace/link/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JsonDiffRoute: typeof JsonDiffRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  JsonToTableRoute: typeof JsonToTableRoute
  JsonViewerRoute: typeof JsonViewerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  GuidesHowToCompareJsonFilesRoute: typeof GuidesHowToCompareJsonFilesRoute
  GuidesHowToFormatJsonRoute: typeof GuidesHowToFormatJsonRoute
  GuidesHowToValidateJsonRoute: typeof GuidesHowToValidateJsonRoute
  GuidesJsonSyntaxExplainedRoute: typeof GuidesJsonSyntaxExplainedRoute
  GuidesJsonVsCsvRoute: typeof GuidesJsonVsCsvRoute
  GuidesReadLargeJsonFilesRoute: typeof GuidesReadLargeJsonFilesRoute
  GuidesViewJsonAsTableRoute: typeof GuidesViewJsonAsTableRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-viewer': {
      id: '/json-viewer'
      path: '/json-viewer'
      fullPath: '/json-viewer'
      preLoaderRoute: typeof JsonViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-table': {
      id: '/json-to-table'
      path: '/json-to-table'
      fullPath: '/json-to-table'
      preLoaderRoute: typeof JsonToTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-diff': {
      id: '/json-diff'
      path: '/json-diff'
      fullPath: '/json-diff'
      preLoaderRoute: typeof JsonDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/view-json-as-table': {
      id: '/guides/view-json-as-table'
      path: '/guides/view-json-as-table'
      fullPath: '/guides/view-json-as-table'
      preLoaderRoute: typeof GuidesViewJsonAsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/read-large-json-files': {
      id: '/guides/read-large-json-files'
      path: '/guides/read-large-json-files'
      fullPath: '/guides/read-large-json-files'
      preLoaderRoute: typeof GuidesReadLargeJsonFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/json-vs-csv': {
      id: '/guides/json-vs-csv'
      path: '/guides/json-vs-csv'
      fullPath: '/guides/json-vs-csv'
      preLoaderRoute: typeof GuidesJsonVsCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/json-syntax-explained': {
      id: '/guides/json-syntax-explained'
      path: '/guides/json-syntax-explained'
      fullPath: '/guides/json-syntax-explained'
      preLoaderRoute: typeof GuidesJsonSyntaxExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-validate-json': {
      id: '/guides/how-to-validate-json'
      path: '/guides/how-to-validate-json'
      fullPath: '/guides/how-to-validate-json'
      preLoaderRoute: typeof GuidesHowToValidateJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-format-json': {
      id: '/guides/how-to-format-json'
      path: '/guides/how-to-format-json'
      fullPath: '/guides/how-to-format-json'
      preLoaderRoute: typeof GuidesHowToFormatJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-compare-json-files': {
      id: '/guides/how-to-compare-json-files'
      path: '/guides/how-to-compare-json-files'
      fullPath: '/guides/how-to-compare-json-files'
      preLoaderRoute: typeof GuidesHowToCompareJsonFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/link/$id': {
      id: '/workspace/link/$id'
      path: '/link/$id'
      fullPath: '/workspace/link/$id'
      preLoaderRoute: typeof WorkspaceLinkIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceLinkIdRoute: typeof WorkspaceLinkIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceLinkIdRoute: WorkspaceLinkIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JsonDiffRoute: JsonDiffRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  JsonToTableRoute: JsonToTableRoute,
  JsonViewerRoute: JsonViewerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  GuidesHowToCompareJsonFilesRoute: GuidesHowToCompareJsonFilesRoute,
  GuidesHowToFormatJsonRoute: GuidesHowToFormatJsonRoute,
  GuidesHowToValidateJsonRoute: GuidesHowToValidateJsonRoute,
  GuidesJsonSyntaxExplainedRoute: GuidesJsonSyntaxExplainedRoute,
  GuidesJsonVsCsvRoute: GuidesJsonVsCsvRoute,
  GuidesReadLargeJsonFilesRoute: GuidesReadLargeJsonFilesRoute,
  GuidesViewJsonAsTableRoute: GuidesViewJsonAsTableRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
